// tslint:disable:max-line-length
import { ImageLoader } from '@sectjs/image-rendering';

const createImageLoader = async () => {
    const loader = new ImageLoader();

    await loader.init([
        ['arrow', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAAMCAIAAADd4huNAAAABnRSTlMAAAAAAABupgeRAAAAP0lEQVR4AYXKoQ0AIBBDUabp/pNgkTgmwB+gLinN9efJ3/4Cjy+QzEfqj5Ufo88xH8k2NNGCJprQuIFK1uHdDpt4bsMHZTF2AAAAAElFTkSuQmCC'],
        ['exchange', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYAQMAAADaua+7AAAAA1BMVEV0dHToufSBAAAAC0lEQVR4AWOgMQAAAGAAATlt6XcAAAAASUVORK5CYII='],
        ['font', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAPwAAAAGAQAAAADP2c61AAAAAnRSTlMAAHaTzTgAAADGSURBVAjXJc2xDsFQFIDho5G4PIHBcHoNvRsPINLZ5DGMGqOlQeI4FQxGQ52p4RUasdXmFbrVZrBIu7iJ/c/3wyxLq0KqV1x6g3l2YyNR3kGA6bqzLIbBHdjohdK4wasRNorNkVC7IUQkC+UwQvTQn8cQd3hJhD21GdHYd2yQhLvzsx7kUFqhKVa4TNL5nWyAoV30k6XzNUT4XwhSzJO45RPx0QWobfu00mgO5EOUpWVDKnVjD1s9Nd1LN2+7W5y9T90Mg/AHw3ZO+24SZDoAAAAASUVORK5CYII='],
        ['grass', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYAgMAAACdGdVrAAAACVBMVEUBphEBnBEBqxEoHYJbAAAAN0lEQVQIHQXBAREAMAgEIH5nACMYxWhGHwCEATQseAAsCgoPFDSAAiAAB0ADCEBxAA4CEwBhwQfCDwLP8EWopAAAAABJRU5ErkJggg=='],
        ['roadCorner', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYAgMAAACdGdVrAAAADFBMVEW3t7coKyovLy//+wDdF/gRAAAAWElEQVR4AVXKAQbAMAxG4UKx2w1eCbqBHqEAdooAdoydr0vTqi3web+E/0WUQthAIMQEHdKAhTr6eTlba0b2kowYmq8xVjCOqkaZNbkfdJUhPjpq427VeQEq8SzVM+Nm4QAAAABJRU5ErkJggg=='],
        ['roadCross', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYAgMAAACdGdVrAAAADFBMVEW3t7coKyr/+wAvLy+IAYq9AAAAUElEQVR4AWNgDY1MDQ2AUaGhN1NLQxliQbxQhtBwCBUaDaEi4dRVMHUVrmTVqpVZq1YBBUEATMUiCaKYUhqJYtjNp2DD4IKxYEEQxXoVyWUADIU377awoDsAAAAASUVORK5CYII='],
        ['roadMain', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYAgMAAACdGdVrAAAADFBMVEW3t7coKyovLy//+wDdF/gRAAAAPUlEQVR4AW3IxQFDAQgD0Cz5andGYt3ad4N49gc6QAqecYN5xPMmz9JqHj/DhUYUah3hyiovt+1Y9NJ29wU5oTFVAB3DvAAAAABJRU5ErkJggg=='],
        ['roadThreeWay', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYAgMAAACdGdVrAAAADFBMVEW3t7coKyovLy//+wDdF/gRAAAAV0lEQVR4AVXIAQaFUBCF4QNvfw/+y8QNmCXcAFrFAFpqqmYSHfj8R98BEIXJMUA0klSANWQOuMjpyAkCQzhg17mvefZBFAi2BapcE/OoSryPeOt38384AWNrNfMPmGOXAAAAAElFTkSuQmCC'],
        ['van', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAYAAAAMCAIAAADONVt5AAAABnRSTlMAAAAAAABupgeRAAAAIUlEQVR4AWMAgg9IAMT/8uULMwRsegYkgFyG/xhgCAkBAO/yxfsWVd6xAAAAAElFTkSuQmCC'],
    ]);

    return loader;
};
export default createImageLoader;
